name: CI Workflow

# Policies run job in branches
on: 
  push: 
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Workflow reference => (NodeJS) pipeline base CI
  golden_ci:
    name: "Continuous Integration"
    uses: gu4-bradseg-devsecops/devsecops-node-workflows/.github/workflows/base-ci.yml@main
    with:
      globals_package_manager: "npm"
      globals_node_version: "18.20.6"
      globals_runner_name: "arc-primary"
      globals_version_app: "1.0.0"

      # Temporary
      job_install_deps_container_runner_image: "node:lts-buster-slim"
      job_build_app_container_runner_image: "node:lts-buster-slim"
      job_build_app_build_args: "run build"
      job_build_image_container_runner_image: "docker:latest"
      job_build_helm_container_runner_image: "docker:latest"
      job_upload_artifacts_container_runner_image: "docker:latest"
      job_upload_artifacts_docker_registry_url: acrdemoarc.azurecr.io
      job_upload_artifacts_helm_repository_url: acrdemoarc.azurecr.io
      job_upload_application_container_runner_image: "alpine:3.14"

    secrets:
      job_upload_artifacts_docker_registry_username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      job_upload_artifacts_docker_registry_password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      job_upload_artifacts_helm_repository_username: ${{ secrets.HELM_REPOSITORY_USERNAME }}
      job_upload_artifacts_helm_repository_password: ${{ secrets.HELM_REPOSITORY_PASSWORD }}
      job_upload_application_kube_config_data:  ${{ secrets.KUBE_CONFIG_DATA }}
